name: Run Telegram Bot

on:
  schedule:
    - cron: '0 8 * * *'  # Каждый день в 8:00
  workflow_dispatch:      # Разрешить ручной запуск

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install requests pdfplumber
        
    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python telegram_energy_bot.py
      
    - name: Upload processed files list as artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed-pdfs
        path: data/
        retention-days: 30
